spring:
  application:
    name: journal
  data:
    mongodb:
      database: journaldb
      host: localhost
      port: 27017
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    configUrl: /v3/api-docs/swagger-config